### ISSUE TITLE
About building in Windows

### ISSUE THREAD

**Issue by jhernancanom** [facebook/luaffifb#21]
Hi, friend.
Can you guide me for building/compiling this in Windows?
My interests: Win32, Lua5.3 .

Thanks.

**Comment by colesbury** [comment]
Check out https://github.com/facebook/luaffifb/pull/13

**Comment by jhernancanom** [comment]
Yes.
Many thanks.

2016-09-08 15:02 GMT-05:00 Sam Gross:

> Check out #13 <https://github.com/facebook/luaffifb/pull/13>
>
> —
>
