### ISSUE TITLE
About using LuaFFI

### ISSUE THREAD

**Issue by jhernancanom** [facebook/luaffifb#22]
[samples.zip.txt](https://github.com/facebook/luaffifb/files/466241/samples.zip.txt)

Hi, friends.
I have wrote several SAMPLE##.LUA for trying LuaFFI; I attached'em.

My scenario is Windows 7, 32 bits, Lua v5.3.3 .

I want to try several .DLLs (I attached'em too) with LuaFFI. I think I go well....but--

With ZLIB1.DLL: well (It seems).

With FSIZEMB.DLL: it runs in Windows without exception error, but the
result is not correct (I tried this .DLL with Alien in Lua v5.1 with correct
result; I also tried the same .DLL in Visual FoxPro and the result is
correct).

With FOCUSIP.DLL:  it runs in Windows without exception error, but the
result is not correct (I do not remember with Alien and Lua v5.1 ; I tried 
the same .DLL in Visual FoxPro with a correct result).

The extension of attached file is .ZIP

Can you (or some one) say me some direction for continue?

Thanks.

**Comment by ggcrunchy** [comment]
Hi. I tried these out.

I didn't see the expected results, but get plausible results. Looks mostly like minor user errors, rather than library problems.

In sample #8 I think you just had operator precedence issues:

```print((sSize/(1024*2)).." Kb")
print((sSize/(1024*1024*2)).." Mb")```

gives me appropriate sizes. (Do you normally have to divide by 2?)

Looking at your other code from alien, maybe this is what you want, in sample #9?

```ffi.cdef[[
unsigned long FOCUSIP(const char *txt);
]]

   local n = 100
   local buf = ffi.new("const char[?]", n)

cRet = lib1.FOCUSIP(buf)

print('\n')
print('La funcion devuelve: ',cRet)

local s = ffi.string(buf)

s = s:match("([%d%.]+)") -- strip stuff after ip

print("ip:", s)```

I couldn't find the FOCUSIP DLL online, so I'm just making a guess about the return value.

**Comment by jhernancanom** [comment]
Hi. Thanks.

>>> In sample #8 <https://github.com/facebook/luaffifb/issues/8> I think
you just had operator precedence issues:

>>> print((sSize/(1024*2)).." Kb")
>>> print((sSize/(1024*1024*2)).." Mb")

>>> gives me appropriate sizes. (Do you normally have to divide by 2?)

The next line shows the expected result:
print("El tamaño es 1,97 Kb")

as you can see in the real file MANUAL.PDF attached. I divide by 2 because
I wanted a (((supposelye))) better aprox result, but no.

print((sSize).." bytes") ---> is showing 11535060 bytes

but the size is 2,021,056 bytes.
---------------------------
About FocusIP: I'll try later......

Thanks, friend.



2016-09-11 18:30 GMT-05:00 Steven Johnson:

**Comment by jhernancanom** [comment]
Hi, friend.

About FocusIP: you are right.

What I need is to know how to use the utility, because --until where I go--
the results were nor right.

Many thanks.
----------------------------------------------------------------------
Say me this:

If you write

ffi.cdef[[
unsigned long FOCUSIP(const char *txt);
]]

why the result is string? I thought 'unsigned long' to be a number.


2016-09-11 18:30 GMT-05:00 Steven Johnson:

> Hi. I tried these out.
>
>    local n = 100
>
>    local buf = ffi.new("const char[?]", n)
>
> cRet = lib1.FOCUSIP(buf)
>
> print('\n')
> print('La funcion devuelve: ',cRet)
>
> local s = ffi.string(buf)
>
> s = s:match("([%d%.]+)") -- strip stuff after ip
>
> print("ip:", s)```
>
> I couldn't find the FOCUSIP DLL online, so I'm just making a guess about the return value.
>
> —
>

**Comment by jhernancanom** [comment]
Steven:

I only find info about ffi.string() in "FFI - API Functions" [[[
http://luajit.org/ext_ffi_api.html ]]]

But I find no examples.

With the knowledge of Alien (that I have) and this info from yours, I'll
try to apply it for a next opprtunity.

Thanks.

**Comment by jhernancanom** [comment]
@ggcrunchy: I think to understand about FocusIP:

The result of the function must be "getted" from the same input parameter. This is something that can not be recognized from the LuaJIT's FFI documentation. Partially from Alien doc... that is why I included something... but ---as you can conclude--- I am not C/C++ expertise developer.

Thanks, ggcrunchy.

**Comment by ggcrunchy** [comment]
Okay, after checking **FSizeMB**'s documentation, I see the problem. **GetFileSize()** really does return a string!

This is what you want in sample #8:

```
ffi.cdef[[
void printf (const char * fmt, ...); // just for testing
const char * GetFileSize(const char *txt);
]]
local mb = lib1.GetFileSize("Manual.pdf")
ffi.C.printf("MB: %s", mb)
```

(Never mind my previous comments about precedence. They were wrong and irrelevant.)

Before, the divided integer gave _close_ numbers, but that was just (bad) luck!

I'm guessing that alien must use integers for some pointers. If you're not familiar with C / C++ I could see this being confusing.

As for the **IPFOCUS()** function... you are seeing a second way to return data in C. The first, as in **GetFileSize()**, was to return it from the function. In this case, you give it some space (a char array) and let it fill that.

Actually, on that note, the **IPFOCUS** stuff shouldn't be **const**, since you're changing them. It's close enough that the ffi matches, but should really be

```
ffi.cdef[[
unsigned long FOCUSIP(char *txt);
]]

   local n = 100
   local buf = ffi.new("char[?]", n)
```

to be correct.

As for **ffi.string()**, it's basically when you need to copy a string out of FFI-land and do something with it using normal Lua. For example, using the string library on it like I did.

**Comment by jhernancanom** [comment]
Yes, @ggcrunchy <https://github.com/ggcrunchy>:
Using this ibfo from you I could complete the samples for "reading" the
info from the two DLLs: from FSizeMB and from FocusIP.

Say you later.

Can you say where can I find the info about *FSizeMB*'s documentation that
you find?



2016-09-11 23:05 GMT-05:00 Steven Johnson:

> Okay, after checking *FSizeMB*'s documentation, I see the problem.
> *GetFileSize()* really does return a string!
>
> This is what you want in sample 8:
>
> ffi.cdef[[
>
>


local ffi = require("ffi")
lib1= ffi.load("FSizeMB.dll")
ffi.cdef[[
void printf (const char * fmt, ...); // just for testing
const char * GetFileSize(const char *txt);
]]
local mb = lib1.GetFileSize("Manual.pdf")
ffi.C.printf("\nusing ffi.C.printf: %s Mb", mb)
      print ("\nin Lua we receive : ", mb)

local s = ffi.string(mb)
s = s:match("([%d%.]+)") -- strip stuff after 'real value'
      print ("\nusing ffi.C.string:", s, " Mb")


print('\n')
for i,v in next, ffi do
   if type(v)=='userdata' then
   print(i,v,string.rep(' ',20),type(i),type(v))
   elseif type(v)=='function' then
   else
   print(i,v,string.rep(' ',20),type(i),type(v))
   end
end
print('\n\n')

--[[

lua: s08.lua:24: bad argument #1 to 'for iterator' (table expected, got userdata)

print('\n\n')
for i,v in next, lib1 do
   if type(v)=='userdata' then
   print(i,v,string.rep(' ',20),type(i),type(v))
   elseif type(v)=='function' then
   else
   print(i,v,string.rep(' ',20),type(i),type(v))
   end
end
print('\n\n')
]]

--

local ffi = require("ffi")
lib1= ffi.load("FocusIP.dll")

ffi.cdef[[
unsigned long FOCUSIP(const char *txt);
]]

   local n = 100
   local buf = ffi.new("const char[?]", n)

cRet = lib1.FOCUSIP(buf)

print('\n')
print('La funcion devuelve: ',cRet)

-- @ggcrunchy said: As for ffi.string(), it's basically when you need to copy a string out of FFI-land 
-- and do something with it using normal Lua. For example, using the string library on it like I did.
-- HCM applies this in the next three lines:
local s = ffi.string(buf)
s = s:match("([%d%.]+)") -- strip stuff after ip
print("ip:", s)

--
print('\n')
for i,v in next, ffi do  -- alien
   --if type(v)=='table' then
   --if not type(v)=='function' then
   if type(v)=='userdata' then
   print(i,v,string.rep(' ',20),type(i),type(v))
   elseif type(v)=='function' then
   else
   print(i,v,string.rep(' ',20),type(i),type(v))
   end
end

print('-----')
print('lib1: ',lib1)
print('-----')

--

**Comment by ggcrunchy** [comment]
The function is mentioned [here](https://www.imagine-programming.com/package/dll-s/fsizemb.html).

For the **FSizeMB** case you don't need the string match. I placed it in the **FocusIP** code since that seemed to fill the rest of the buffer with garbage, so I only used the part that was a sequence of digits and (non-magic) dot characters (thus that mysterious-looking [pattern](http://www.lua.org/manual/5.3/manual.html#6.4.1)).

**Comment by jhernancanom** [comment]
Yes, @ggcrunchy <https://github.com/ggcrunchy>.
>>> For the *FSizeMB* case you don't need the string match.

I consider you say this because you are using *ffi.C.printf()* and *void
printf (const char * fmt, ...); // just for testing *inside *ffi.cdef* .

But I prefer to use the vble that you call *mb* to get the result.



2016-09-12 1:21 GMT-05:00 Steven Johnson:

**Comment by jhernancanom** [comment]
Hello, @ggcrunchy <https://github.com/ggcrunchy>.

I have found that local s = ffi.string(buf) yes it is necessary. Look at
the sample09.lua attached.

If I don't use it, the vble buf has "no meaning info".

Thanks, friend.


local ffi = require("ffi")
lib1= ffi.load("FocusIP.dll")

ffi.cdef[[
unsigned long FOCUSIP(const char *txt);
]]

   local n = 100
   local buf = ffi.new("const char[?]", n)

cRet = lib1.FOCUSIP(buf)

print('\n')
print('La funcion devuelve: ',cRet)
*print('el parametro tiene : ',buf )*

local s = ffi.string(buf)

s = s:match("([%d%.]+)") -- strip stuff after ip

print("ip:", s)

--

**Comment by ggcrunchy** [comment]
I only meant that you had copied the

```
s = s:match("([%d%.]+)") -- strip stuff after ip
```

into sample #8. It's actually harmless there, since the string is compatible, but unnecessary, and would give you problems with "normal" strings like text.

**Comment by jhernancanom** [comment]
Yes.

s = s:match("([%d%.]+)")

  -- not necessary in FSizeMB

  -- yes necessary in FocusIP

Thanks.

2016-09-12 11:28 GMT-05:00 Steven Johnson:
