### ISSUE TITLE
Unable to compile on arm

### ISSUE THREAD

**Issue by SyRenity** [facebook/luaffifb#6]
Trying to compile on Jetson TK1 as part of torch, getting error due to missing call_arm.h.

Generating the call_arm.h manually via:
luajit dynasm/dynasm.lua -LN -o call_arm.h call_arm.dasc 

and trying to compile it brings following errror:
```
In file included from call.c:47:0:
call_arm.h:633:64: error: unknown type name ‘function_t’
 static void compile_extern_jump(struct jit* jit, lua_State* L, function_t func, uint8_t* code)
                                                                ^
call_arm.h:655:1: error: unknown type name ‘function_t’
 function_t push_callback(struct jit* jit, lua_State* L, int fidx, int ct_usr, const struct ctype* ct)
 ^
call_arm.h:655:12: error: conflicting types for ‘push_callback’
 function_t push_callback(struct jit* jit, lua_State* L, int fidx, int ct_usr, const struct ctype* ct)
            ^
In file included from call.c:9:0:
ffi.h:406:6: note: previous declaration of ‘push_callback’ was here
 void push_callback(lua_State* L, cfunction luafunc, cfunction cfunc);
      ^
In file included from call.c:47:0:
call_arm.h: In function ‘push_callback’:
call_arm.h:700:18: error: ‘UINT64_TYPE’ undeclared (first use in this function)
             case UINT64_TYPE:
...
```

Any ideas?

**Comment by colesbury** [comment]
There's a bunch of changes that were made to call_x86.dasc that need to be made to call_arm.dasc

Compare:
https://github.com/facebook/luaffifb/commits/master/call_arm.dasc
https://github.com/facebook/luaffifb/commits/master/call_x86.dasc

Pull requests welcome

**Comment by colesbury** [comment]
I've fixed the compilation errors on ARM, which should make the Torch distro installation work. LuaFFI still doesn't actually work properly on ARM, but this doesn't matter if you're using the LuaJIT version of Torch.
