### ISSUE TITLE
internal error: missing link for to_typed_pointer

### ISSUE THREAD

**Issue by tencherry10** [facebook/luaffifb#9]
Hi,

When I try to run test.lua inside luaffifb on a ARM processor (Beagle Bone Black). I get the following error:

```
lua: test.lua:346: internal error: missing link for to_typed_pointer
stack traceback:
        [C]: in metamethod '__index'
        test.lua:346: in main chunk
        [C]: in ?
```

I am running ARM (debian wheezy) w/ ```gcc (Debian 4.6.3-14) 4.6.3```. When, I run test.lua using my PC machine. I have no problems (I get test PASSED). 

Any ideas on how I can fix this?

**Comment by colesbury** [comment]
ARM is not currently supported. As an alternative, you can use LuaJIT (luajit.org) with its built-in FFI.

**Comment by tencherry10** [comment]
Ok, it was a bad assumption on my part then. I had just assumed ARM is supported b/c of the `call_arm.h` and `call_arm.dasc` files.

Thanks for the rapid reply!
